// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client-coin.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//上分
type TopupReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value                int64      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TopupReq) Reset()         { *m = TopupReq{} }
func (m *TopupReq) String() string { return proto.CompactTextString(m) }
func (*TopupReq) ProtoMessage()    {}
func (*TopupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_992fecc01331446d, []int{0}
}

func (m *TopupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopupReq.Unmarshal(m, b)
}
func (m *TopupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopupReq.Marshal(b, m, deterministic)
}
func (m *TopupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopupReq.Merge(m, src)
}
func (m *TopupReq) XXX_Size() int {
	return xxx_messageInfo_TopupReq.Size(m)
}
func (m *TopupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TopupReq.DiscardUnknown(m)
}

var xxx_messageInfo_TopupReq proto.InternalMessageInfo

func (m *TopupReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TopupReq) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TopupAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	OrderNo              string     `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TopupAck) Reset()         { *m = TopupAck{} }
func (m *TopupAck) String() string { return proto.CompactTextString(m) }
func (*TopupAck) ProtoMessage()    {}
func (*TopupAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_992fecc01331446d, []int{1}
}

func (m *TopupAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopupAck.Unmarshal(m, b)
}
func (m *TopupAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopupAck.Marshal(b, m, deterministic)
}
func (m *TopupAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopupAck.Merge(m, src)
}
func (m *TopupAck) XXX_Size() int {
	return xxx_messageInfo_TopupAck.Size(m)
}
func (m *TopupAck) XXX_DiscardUnknown() {
	xxx_messageInfo_TopupAck.DiscardUnknown(m)
}

var xxx_messageInfo_TopupAck proto.InternalMessageInfo

func (m *TopupAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TopupAck) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type WithdrawReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value                int64      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawReq) Reset()         { *m = WithdrawReq{} }
func (m *WithdrawReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawReq) ProtoMessage()    {}
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_992fecc01331446d, []int{2}
}

func (m *WithdrawReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReq.Unmarshal(m, b)
}
func (m *WithdrawReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReq.Marshal(b, m, deterministic)
}
func (m *WithdrawReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReq.Merge(m, src)
}
func (m *WithdrawReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawReq.Size(m)
}
func (m *WithdrawReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReq proto.InternalMessageInfo

func (m *WithdrawReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WithdrawReq) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type WithdrawAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	OrderNo              string     `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawAck) Reset()         { *m = WithdrawAck{} }
func (m *WithdrawAck) String() string { return proto.CompactTextString(m) }
func (*WithdrawAck) ProtoMessage()    {}
func (*WithdrawAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_992fecc01331446d, []int{3}
}

func (m *WithdrawAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawAck.Unmarshal(m, b)
}
func (m *WithdrawAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawAck.Marshal(b, m, deterministic)
}
func (m *WithdrawAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawAck.Merge(m, src)
}
func (m *WithdrawAck) XXX_Size() int {
	return xxx_messageInfo_WithdrawAck.Size(m)
}
func (m *WithdrawAck) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawAck.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawAck proto.InternalMessageInfo

func (m *WithdrawAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WithdrawAck) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func init() {
	proto.RegisterType((*TopupReq)(nil), "protocol.TopupReq")
	proto.RegisterType((*TopupAck)(nil), "protocol.TopupAck")
	proto.RegisterType((*WithdrawReq)(nil), "protocol.WithdrawReq")
	proto.RegisterType((*WithdrawAck)(nil), "protocol.WithdrawAck")
}

func init() { proto.RegisterFile("client-coin.proto", fileDescriptor_992fecc01331446d) }

var fileDescriptor_992fecc01331446d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x4d, 0xce, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x52, 0x3c, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x10, 0x71, 0x25, 0x5f,
	0x2e, 0x8e, 0x90, 0xfc, 0x82, 0xd2, 0x82, 0xa0, 0xd4, 0x42, 0x21, 0x6d, 0x2e, 0x36, 0x88, 0x9c,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb0, 0x1e, 0x4c, 0x93, 0x5e, 0x50, 0x6a, 0xa1, 0x07,
	0x58, 0x2a, 0x08, 0xaa, 0x44, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x49,
	0x81, 0x51, 0x83, 0x39, 0x08, 0xc2, 0x51, 0x0a, 0x84, 0x1a, 0xe7, 0x98, 0x9c, 0x8d, 0xcf, 0x38,
	0xc7, 0xe4, 0x6c, 0x34, 0xe3, 0x24, 0xb8, 0xd8, 0xf3, 0x8b, 0x52, 0x52, 0x8b, 0xfc, 0xf2, 0xc1,
	0x06, 0x72, 0x06, 0xc1, 0xb8, 0x4a, 0x01, 0x5c, 0xdc, 0xe1, 0x99, 0x25, 0x19, 0x29, 0x45, 0x89,
	0xe5, 0x54, 0x72, 0x64, 0x08, 0xc2, 0x44, 0xea, 0xb9, 0x33, 0x89, 0x0d, 0xac, 0xcb, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0x94, 0x9b, 0x9d, 0x7d, 0x01, 0x00, 0x00,
}
