// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client-chat.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendToUserReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 string     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Kind                 int32      `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Extra                string     `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	UserId               int64      `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendToUserReq) Reset()         { *m = SendToUserReq{} }
func (m *SendToUserReq) String() string { return proto.CompactTextString(m) }
func (*SendToUserReq) ProtoMessage()    {}
func (*SendToUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9f1f91501c061ef, []int{0}
}

func (m *SendToUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToUserReq.Unmarshal(m, b)
}
func (m *SendToUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToUserReq.Marshal(b, m, deterministic)
}
func (m *SendToUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToUserReq.Merge(m, src)
}
func (m *SendToUserReq) XXX_Size() int {
	return xxx_messageInfo_SendToUserReq.Size(m)
}
func (m *SendToUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendToUserReq proto.InternalMessageInfo

func (m *SendToUserReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SendToUserReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SendToUserReq) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *SendToUserReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *SendToUserReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SendToRoomReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 string     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Kind                 int32      `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Extra                string     `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	RoomId               int64      `protobuf:"varint,5,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendToRoomReq) Reset()         { *m = SendToRoomReq{} }
func (m *SendToRoomReq) String() string { return proto.CompactTextString(m) }
func (*SendToRoomReq) ProtoMessage()    {}
func (*SendToRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9f1f91501c061ef, []int{1}
}

func (m *SendToRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToRoomReq.Unmarshal(m, b)
}
func (m *SendToRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToRoomReq.Marshal(b, m, deterministic)
}
func (m *SendToRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToRoomReq.Merge(m, src)
}
func (m *SendToRoomReq) XXX_Size() int {
	return xxx_messageInfo_SendToRoomReq.Size(m)
}
func (m *SendToRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendToRoomReq proto.InternalMessageInfo

func (m *SendToRoomReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SendToRoomReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SendToRoomReq) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *SendToRoomReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *SendToRoomReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type BoardcastReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 string     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Kind                 int32      `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Extra                string     `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BoardcastReq) Reset()         { *m = BoardcastReq{} }
func (m *BoardcastReq) String() string { return proto.CompactTextString(m) }
func (*BoardcastReq) ProtoMessage()    {}
func (*BoardcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9f1f91501c061ef, []int{2}
}

func (m *BoardcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardcastReq.Unmarshal(m, b)
}
func (m *BoardcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardcastReq.Marshal(b, m, deterministic)
}
func (m *BoardcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardcastReq.Merge(m, src)
}
func (m *BoardcastReq) XXX_Size() int {
	return xxx_messageInfo_BoardcastReq.Size(m)
}
func (m *BoardcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardcastReq proto.InternalMessageInfo

func (m *BoardcastReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BoardcastReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *BoardcastReq) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *BoardcastReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*SendToUserReq)(nil), "protocol.SendToUserReq")
	proto.RegisterType((*SendToRoomReq)(nil), "protocol.SendToRoomReq")
	proto.RegisterType((*BoardcastReq)(nil), "protocol.BoardcastReq")
}

func init() { proto.RegisterFile("client-chat.proto", fileDescriptor_e9f1f91501c061ef) }

var fileDescriptor_e9f1f91501c061ef = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x4d, 0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x52, 0x3c, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x10, 0x71, 0xa5, 0x49,
	0x8c, 0x5c, 0xbc, 0xc1, 0xa9, 0x79, 0x29, 0x21, 0xf9, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0xa9, 0x85,
	0x42, 0xda, 0x5c, 0x6c, 0x10, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x30,
	0xad, 0x7a, 0x41, 0xa9, 0x85, 0x1e, 0x60, 0xa9, 0x20, 0xa8, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xa4,
	0xfc, 0x94, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0x96, 0x9d, 0x99,
	0x97, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0xa6, 0x56,
	0x94, 0x14, 0x25, 0x4a, 0xb0, 0x80, 0x15, 0x42, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9,
	0x45, 0x9e, 0x29, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x50, 0x1e, 0x92, 0xa3, 0x82, 0xf2,
	0xf3, 0x73, 0xe9, 0xef, 0xa8, 0xa2, 0xfc, 0xfc, 0x5c, 0x84, 0xa3, 0x20, 0x3c, 0xa5, 0x4a, 0x2e,
	0x1e, 0xa7, 0xfc, 0xc4, 0xa2, 0x94, 0xe4, 0xc4, 0xe2, 0x12, 0xfa, 0x3a, 0x29, 0x89, 0x0d, 0x6c,
	0xb2, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x35, 0xd1, 0x5e, 0x33, 0xd8, 0x01, 0x00, 0x00,
}
