// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqHeader struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Mid                  int32    `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{0}
}

func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (m *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(m, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ReqHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReqHeader) GetMid() int32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

type AckHeader struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Mid                  int32    `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckHeader) Reset()         { *m = AckHeader{} }
func (m *AckHeader) String() string { return proto.CompactTextString(m) }
func (*AckHeader) ProtoMessage()    {}
func (*AckHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{1}
}

func (m *AckHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckHeader.Unmarshal(m, b)
}
func (m *AckHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckHeader.Marshal(b, m, deterministic)
}
func (m *AckHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckHeader.Merge(m, src)
}
func (m *AckHeader) XXX_Size() int {
	return xxx_messageInfo_AckHeader.Size(m)
}
func (m *AckHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_AckHeader.DiscardUnknown(m)
}

var xxx_messageInfo_AckHeader proto.InternalMessageInfo

func (m *AckHeader) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AckHeader) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AckHeader) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AckHeader) GetMid() int32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

type NotiHeader struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotiHeader) Reset()         { *m = NotiHeader{} }
func (m *NotiHeader) String() string { return proto.CompactTextString(m) }
func (*NotiHeader) ProtoMessage()    {}
func (*NotiHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{2}
}

func (m *NotiHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotiHeader.Unmarshal(m, b)
}
func (m *NotiHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotiHeader.Marshal(b, m, deterministic)
}
func (m *NotiHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotiHeader.Merge(m, src)
}
func (m *NotiHeader) XXX_Size() int {
	return xxx_messageInfo_NotiHeader.Size(m)
}
func (m *NotiHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_NotiHeader.DiscardUnknown(m)
}

var xxx_messageInfo_NotiHeader proto.InternalMessageInfo

func (m *NotiHeader) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type CallAck struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallAck) Reset()         { *m = CallAck{} }
func (m *CallAck) String() string { return proto.CompactTextString(m) }
func (*CallAck) ProtoMessage()    {}
func (*CallAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{3}
}

func (m *CallAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallAck.Unmarshal(m, b)
}
func (m *CallAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallAck.Marshal(b, m, deterministic)
}
func (m *CallAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallAck.Merge(m, src)
}
func (m *CallAck) XXX_Size() int {
	return xxx_messageInfo_CallAck.Size(m)
}
func (m *CallAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CallAck.DiscardUnknown(m)
}

var xxx_messageInfo_CallAck proto.InternalMessageInfo

func (m *CallAck) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CallAck) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHeader)(nil), "protocol.ReqHeader")
	proto.RegisterType((*AckHeader)(nil), "protocol.AckHeader")
	proto.RegisterType((*NotiHeader)(nil), "protocol.NotiHeader")
	proto.RegisterType((*CallAck)(nil), "protocol.CallAck")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_6398613e36d6c2ce) }

var fileDescriptor_6398613e36d6c2ce = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a,
	0xae, 0x5c, 0x9c, 0x41, 0xa9, 0x85, 0x1e, 0x60, 0x49, 0x21, 0x01, 0x2e, 0xe6, 0xd2, 0xcc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x3f, 0x3b,
	0x35, 0x4f, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x01, 0xa9, 0xcb, 0xcd, 0x4c, 0x91,
	0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x95, 0x42, 0xb9, 0x38, 0x1d, 0x93, 0xb3, 0xa1,
	0xc6, 0x08, 0x71, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x82, 0xcd, 0x61, 0x0d, 0x02, 0xb3, 0xc1, 0x5a,
	0x8a, 0xd3, 0xa1, 0xc6, 0x80, 0x98, 0x30, 0xcb, 0x98, 0x11, 0x96, 0x41, 0x8d, 0x65, 0x41, 0x18,
	0x2b, 0xc7, 0xc5, 0xe5, 0x97, 0x5f, 0x92, 0x89, 0xcb, 0x79, 0x4a, 0xfa, 0x5c, 0xec, 0xce, 0x89,
	0x39, 0x39, 0x8e, 0xc9, 0xd9, 0xc4, 0x59, 0x9a, 0xc4, 0x06, 0xf6, 0xb8, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x84, 0x97, 0x89, 0x3d, 0x0f, 0x01, 0x00, 0x00,
}
