// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client-game.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGameRoomTypeListReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	GameId               int32      `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetGameRoomTypeListReq) Reset()         { *m = GetGameRoomTypeListReq{} }
func (m *GetGameRoomTypeListReq) String() string { return proto.CompactTextString(m) }
func (*GetGameRoomTypeListReq) ProtoMessage()    {}
func (*GetGameRoomTypeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{0}
}

func (m *GetGameRoomTypeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameRoomTypeListReq.Unmarshal(m, b)
}
func (m *GetGameRoomTypeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameRoomTypeListReq.Marshal(b, m, deterministic)
}
func (m *GetGameRoomTypeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameRoomTypeListReq.Merge(m, src)
}
func (m *GetGameRoomTypeListReq) XXX_Size() int {
	return xxx_messageInfo_GetGameRoomTypeListReq.Size(m)
}
func (m *GetGameRoomTypeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameRoomTypeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameRoomTypeListReq proto.InternalMessageInfo

func (m *GetGameRoomTypeListReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetGameRoomTypeListReq) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GetGameRoomTypeListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetGameRoomTypeListAck struct {
	Header               *AckHeader                             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	GameId               int32                                  `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Items                []*GetGameRoomTypeListAck_GameTypeItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetGameRoomTypeListAck) Reset()         { *m = GetGameRoomTypeListAck{} }
func (m *GetGameRoomTypeListAck) String() string { return proto.CompactTextString(m) }
func (*GetGameRoomTypeListAck) ProtoMessage()    {}
func (*GetGameRoomTypeListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{1}
}

func (m *GetGameRoomTypeListAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameRoomTypeListAck.Unmarshal(m, b)
}
func (m *GetGameRoomTypeListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameRoomTypeListAck.Marshal(b, m, deterministic)
}
func (m *GetGameRoomTypeListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameRoomTypeListAck.Merge(m, src)
}
func (m *GetGameRoomTypeListAck) XXX_Size() int {
	return xxx_messageInfo_GetGameRoomTypeListAck.Size(m)
}
func (m *GetGameRoomTypeListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameRoomTypeListAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameRoomTypeListAck proto.InternalMessageInfo

func (m *GetGameRoomTypeListAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetGameRoomTypeListAck) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GetGameRoomTypeListAck) GetItems() []*GetGameRoomTypeListAck_GameTypeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetGameRoomTypeListAck_GameTypeItem struct {
	GameType             int32    `protobuf:"varint,1,opt,name=gameType,proto3" json:"gameType,omitempty"`
	GameInfo             string   `protobuf:"bytes,2,opt,name=gameInfo,proto3" json:"gameInfo,omitempty"`
	Extra                string   `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameRoomTypeListAck_GameTypeItem) Reset()         { *m = GetGameRoomTypeListAck_GameTypeItem{} }
func (m *GetGameRoomTypeListAck_GameTypeItem) String() string { return proto.CompactTextString(m) }
func (*GetGameRoomTypeListAck_GameTypeItem) ProtoMessage()    {}
func (*GetGameRoomTypeListAck_GameTypeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{1, 0}
}

func (m *GetGameRoomTypeListAck_GameTypeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem.Unmarshal(m, b)
}
func (m *GetGameRoomTypeListAck_GameTypeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem.Marshal(b, m, deterministic)
}
func (m *GetGameRoomTypeListAck_GameTypeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem.Merge(m, src)
}
func (m *GetGameRoomTypeListAck_GameTypeItem) XXX_Size() int {
	return xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem.Size(m)
}
func (m *GetGameRoomTypeListAck_GameTypeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameRoomTypeListAck_GameTypeItem proto.InternalMessageInfo

func (m *GetGameRoomTypeListAck_GameTypeItem) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GetGameRoomTypeListAck_GameTypeItem) GetGameInfo() string {
	if m != nil {
		return m.GameInfo
	}
	return ""
}

func (m *GetGameRoomTypeListAck_GameTypeItem) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type EnterGameReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	GameId               int32      `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	GameType             int32      `protobuf:"varint,3,opt,name=gameType,proto3" json:"gameType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnterGameReq) Reset()         { *m = EnterGameReq{} }
func (m *EnterGameReq) String() string { return proto.CompactTextString(m) }
func (*EnterGameReq) ProtoMessage()    {}
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{2}
}

func (m *EnterGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameReq.Unmarshal(m, b)
}
func (m *EnterGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameReq.Marshal(b, m, deterministic)
}
func (m *EnterGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameReq.Merge(m, src)
}
func (m *EnterGameReq) XXX_Size() int {
	return xxx_messageInfo_EnterGameReq.Size(m)
}
func (m *EnterGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameReq proto.InternalMessageInfo

func (m *EnterGameReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EnterGameReq) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *EnterGameReq) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

type EnterGameAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnterGameAck) Reset()         { *m = EnterGameAck{} }
func (m *EnterGameAck) String() string { return proto.CompactTextString(m) }
func (*EnterGameAck) ProtoMessage()    {}
func (*EnterGameAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{3}
}

func (m *EnterGameAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameAck.Unmarshal(m, b)
}
func (m *EnterGameAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameAck.Marshal(b, m, deterministic)
}
func (m *EnterGameAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameAck.Merge(m, src)
}
func (m *EnterGameAck) XXX_Size() int {
	return xxx_messageInfo_EnterGameAck.Size(m)
}
func (m *EnterGameAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameAck.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameAck proto.InternalMessageInfo

func (m *EnterGameAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ExitGameReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExitGameReq) Reset()         { *m = ExitGameReq{} }
func (m *ExitGameReq) String() string { return proto.CompactTextString(m) }
func (*ExitGameReq) ProtoMessage()    {}
func (*ExitGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{4}
}

func (m *ExitGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitGameReq.Unmarshal(m, b)
}
func (m *ExitGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitGameReq.Marshal(b, m, deterministic)
}
func (m *ExitGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitGameReq.Merge(m, src)
}
func (m *ExitGameReq) XXX_Size() int {
	return xxx_messageInfo_ExitGameReq.Size(m)
}
func (m *ExitGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitGameReq proto.InternalMessageInfo

func (m *ExitGameReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ExitGameAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExitGameAck) Reset()         { *m = ExitGameAck{} }
func (m *ExitGameAck) String() string { return proto.CompactTextString(m) }
func (*ExitGameAck) ProtoMessage()    {}
func (*ExitGameAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f4ba40ff05b740, []int{5}
}

func (m *ExitGameAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitGameAck.Unmarshal(m, b)
}
func (m *ExitGameAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitGameAck.Marshal(b, m, deterministic)
}
func (m *ExitGameAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitGameAck.Merge(m, src)
}
func (m *ExitGameAck) XXX_Size() int {
	return xxx_messageInfo_ExitGameAck.Size(m)
}
func (m *ExitGameAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitGameAck.DiscardUnknown(m)
}

var xxx_messageInfo_ExitGameAck proto.InternalMessageInfo

func (m *ExitGameAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*GetGameRoomTypeListReq)(nil), "protocol.GetGameRoomTypeListReq")
	proto.RegisterType((*GetGameRoomTypeListAck)(nil), "protocol.GetGameRoomTypeListAck")
	proto.RegisterType((*GetGameRoomTypeListAck_GameTypeItem)(nil), "protocol.GetGameRoomTypeListAck.GameTypeItem")
	proto.RegisterType((*EnterGameReq)(nil), "protocol.EnterGameReq")
	proto.RegisterType((*EnterGameAck)(nil), "protocol.EnterGameAck")
	proto.RegisterType((*ExitGameReq)(nil), "protocol.ExitGameReq")
	proto.RegisterType((*ExitGameAck)(nil), "protocol.ExitGameAck")
}

func init() { proto.RegisterFile("client-game.proto", fileDescriptor_84f4ba40ff05b740) }

var fileDescriptor_84f4ba40ff05b740 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x49, 0x63, 0x42, 0xfb, 0x92, 0xc5, 0x53, 0x4a, 0xc8, 0x14, 0x6e, 0x0a, 0x48, 0x33,
	0xd4, 0x4d, 0xa7, 0x22, 0xa5, 0x06, 0xc4, 0xe1, 0x70, 0x74, 0x39, 0xd3, 0x67, 0x0d, 0xed, 0xe5,
	0x9a, 0xf4, 0x0d, 0x75, 0xf3, 0x4f, 0x97, 0x5c, 0xd2, 0x1a, 0xa1, 0x88, 0x11, 0xa7, 0xbb, 0xef,
	0xfb, 0xf5, 0xf9, 0xf2, 0x85, 0xf3, 0x6c, 0x93, 0x63, 0x41, 0x93, 0x95, 0x54, 0x98, 0x6c, 0x2b,
	0x4d, 0x9a, 0x0d, 0xcd, 0x93, 0xe9, 0x4d, 0xe8, 0xbf, 0xa1, 0x5c, 0x62, 0xd5, 0xd4, 0x79, 0x09,
	0xe3, 0x05, 0xd2, 0x42, 0x2a, 0x14, 0x5a, 0xab, 0xa7, 0xf7, 0x2d, 0x3e, 0xe4, 0x3b, 0x12, 0x58,
	0xb2, 0x2b, 0x70, 0x9b, 0xc9, 0xc0, 0x8a, 0xac, 0xd8, 0x9b, 0x5e, 0x24, 0x87, 0x13, 0x89, 0xc0,
	0xf2, 0xde, 0xb4, 0x44, 0x3b, 0xc2, 0xc6, 0xe0, 0xd6, 0xb0, 0x74, 0x19, 0x0c, 0x22, 0x2b, 0x76,
	0x44, 0xab, 0x18, 0x83, 0xb3, 0x47, 0xa9, 0x30, 0xb0, 0x23, 0x2b, 0x1e, 0x09, 0xf3, 0xe7, 0x1f,
	0x83, 0x93, 0xcc, 0x59, 0xb6, 0xfe, 0x89, 0x39, 0xcb, 0xd6, 0xbf, 0x64, 0xde, 0x81, 0x93, 0x13,
	0xaa, 0x5d, 0x60, 0x47, 0x76, 0xec, 0x4d, 0x27, 0x5f, 0x37, 0x4e, 0x53, 0x93, 0xba, 0x56, 0xeb,
	0x94, 0x50, 0x89, 0x66, 0x37, 0x7c, 0x06, 0xbf, 0x5b, 0x66, 0x21, 0x0c, 0x57, 0xad, 0x36, 0xde,
	0x1c, 0x71, 0xd4, 0x87, 0x5e, 0x5a, 0xbc, 0x6a, 0x63, 0x65, 0x24, 0x8e, 0x9a, 0x5d, 0x82, 0x83,
	0x7b, 0xaa, 0x64, 0x9b, 0x40, 0x23, 0xb8, 0x06, 0x7f, 0x5e, 0x10, 0x56, 0xc6, 0xcd, 0x7f, 0x65,
	0xdd, 0xb5, 0x68, 0x7f, 0xb7, 0xc8, 0x6f, 0x3b, 0xc0, 0xbe, 0x41, 0xf3, 0x1b, 0xf0, 0xe6, 0xfb,
	0x9c, 0xfe, 0x62, 0xb6, 0xbb, 0xdb, 0x97, 0xfb, 0xe2, 0x9a, 0xde, 0xf5, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x77, 0x3a, 0x6e, 0xaa, 0xcf, 0x02, 0x00, 0x00,
}
