// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client-notify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from client-notify.proto</summary>
  public static partial class ClientNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for client-notify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjbGllbnQtbm90aWZ5LnByb3RvEghwcm90b2NvbBoMaGVhZGVyLnByb3Rv",
            "IpEBCg1NZXNzYWdlTm90aWZ5EiQKBmhlYWRlchgBIAEoCzIULnByb3RvY29s",
            "Lk5vdGlIZWFkZXISDAoEYm9keRgCIAEoCRINCgVtVHlwZRgDIAEoBRIMCgRr",
            "aW5kGAQgASgFEg0KBWV4dHJhGAUgASgJEg4KBnVzZXJJZBgGIAEoAxIQCgh1",
            "c2VyTmFtZRgHIAEoAzJMCg1Ob3RpZnlTZXJ2aWNlEjsKC1B1c2hNZXNzYWdl",
            "EhcucHJvdG9jb2wuTWVzc2FnZU5vdGlmeRoRLnByb3RvY29sLkNhbGxBY2si",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protocol.HeaderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.MessageNotify), global::Protocol.MessageNotify.Parser, new[]{ "Header", "Body", "MType", "Kind", "Extra", "UserId", "UserName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MessageNotify : pb::IMessage<MessageNotify> {
    private static readonly pb::MessageParser<MessageNotify> _parser = new pb::MessageParser<MessageNotify>(() => new MessageNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ClientNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageNotify(MessageNotify other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      body_ = other.body_;
      mType_ = other.mType_;
      kind_ = other.kind_;
      extra_ = other.extra_;
      userId_ = other.userId_;
      userName_ = other.userName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageNotify Clone() {
      return new MessageNotify(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Protocol.NotiHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protocol.NotiHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private string body_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mType" field.</summary>
    public const int MTypeFieldNumber = 3;
    private int mType_;
    /// <summary>
    ///消息来源 1=系统消息 2=好友消息 3=房间消息 4=广播消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MType {
      get { return mType_; }
      set {
        mType_ = value;
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 4;
    private int kind_;
    /// <summary>
    ///消息类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 5;
    private string extra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Extra {
      get { return extra_; }
      set {
        extra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 6;
    private long userId_;
    /// <summary>
    ///消息发送者
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 7;
    private long userName_;
    /// <summary>
    ///消息发送者
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserName {
      get { return userName_; }
      set {
        userName_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (Body != other.Body) return false;
      if (MType != other.MType) return false;
      if (Kind != other.Kind) return false;
      if (Extra != other.Extra) return false;
      if (UserId != other.UserId) return false;
      if (UserName != other.UserName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      if (MType != 0) hash ^= MType.GetHashCode();
      if (Kind != 0) hash ^= Kind.GetHashCode();
      if (Extra.Length != 0) hash ^= Extra.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (UserName != 0L) hash ^= UserName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Body);
      }
      if (MType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MType);
      }
      if (Kind != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Kind);
      }
      if (Extra.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Extra);
      }
      if (UserId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(UserId);
      }
      if (UserName != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(UserName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Body);
      }
      if (MType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MType);
      }
      if (Kind != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Kind);
      }
      if (Extra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Extra);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (UserName != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageNotify other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Protocol.NotiHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      if (other.MType != 0) {
        MType = other.MType;
      }
      if (other.Kind != 0) {
        Kind = other.Kind;
      }
      if (other.Extra.Length != 0) {
        Extra = other.Extra;
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.UserName != 0L) {
        UserName = other.UserName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Protocol.NotiHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            Body = input.ReadString();
            break;
          }
          case 24: {
            MType = input.ReadInt32();
            break;
          }
          case 32: {
            Kind = input.ReadInt32();
            break;
          }
          case 42: {
            Extra = input.ReadString();
            break;
          }
          case 48: {
            UserId = input.ReadInt64();
            break;
          }
          case 56: {
            UserName = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
